City.create(name:"Denver", description: nil)
Coordinate.create(lat:39.7392, lon:-104.9847, latlon:-104.9847, locatable_id:1, locatable_type:'City')

Neighborhood.create(name:"Chaffee Park", description: nil, city_id:1)
Neighborhood.create(name:"Sunnyside", description: nil, city_id:1)
Neighborhood.create(name:"Highland", description: nil, city_id:1)
Neighborhood.create(name:"Globeville", description: nil, city_id:1)
Neighborhood.create(name:"Jefferson Park", description: nil, city_id:1)
Neighborhood.create(name:"Sun Valley", description: nil, city_id:1)
Neighborhood.create(name:"Valverde", description: nil, city_id:1)
Neighborhood.create(name:"Athmar Park", description: nil, city_id:1)
Neighborhood.create(name:"Windsor", description: nil, city_id:1)
Neighborhood.create(name:"Northeast Park Hill", description: nil, city_id:1)
Neighborhood.create(name:"Elyria Swansea", description: nil, city_id:1)
Neighborhood.create(name:"Wellshire", description: nil, city_id:1)
Neighborhood.create(name:"University", description: nil, city_id:1)
Neighborhood.create(name:"Rosedale", description: nil, city_id:1)
Neighborhood.create(name:"Cheesman Park", description: nil, city_id:1)
Neighborhood.create(name:"Hilltop", description: nil, city_id:1)
Neighborhood.create(name:"Montclair", description: nil, city_id:1)
Neighborhood.create(name:"Hale", description: nil, city_id:1)
Neighborhood.create(name:"North Park Hill", description: nil, city_id:1)
Neighborhood.create(name:"South Park Hill", description: nil, city_id:1)
Neighborhood.create(name:"University Park", description: nil, city_id:1)
Neighborhood.create(name:"Platt Park", description: nil, city_id:1)
Neighborhood.create(name:"College View - South Platte", description: nil, city_id:1)
Neighborhood.create(name:"Overland", description: nil, city_id:1)
Neighborhood.create(name:"Ruby Hill", description: nil, city_id:1)
Neighborhood.create(name:"Kennedy", description: nil, city_id:1)
Neighborhood.create(name:"Hampden", description: nil, city_id:1)
Neighborhood.create(name:"Baker", description: nil, city_id:1)
Neighborhood.create(name:"Fort Logan", description: nil, city_id:1)
Neighborhood.create(name:"Bear Valley", description: nil, city_id:1)
Neighborhood.create(name:"Harvey Park South", description: nil, city_id:1)
Neighborhood.create(name:"Southmoor Park", description: nil, city_id:1)
Neighborhood.create(name:"Hampden South", description: nil, city_id:1)
Neighborhood.create(name:"Indian Creek", description: nil, city_id:1)
Neighborhood.create(name:"Goldsmith", description: nil, city_id:1)
Neighborhood.create(name:"Virginia Village", description: nil, city_id:1)
Neighborhood.create(name:"Gateway - Green Valley Ranch", description: nil, city_id:1)
Neighborhood.create(name:"DIA", description: nil, city_id:1)
Neighborhood.create(name:"University Hills", description: nil, city_id:1)
Neighborhood.create(name:"Harvey Park", description: nil, city_id:1)
Neighborhood.create(name:"Mar Lee", description: nil, city_id:1)
Neighborhood.create(name:"Westwood", description: nil, city_id:1)
Neighborhood.create(name:"East Colfax", description: nil, city_id:1)
Neighborhood.create(name:"Auraria", description: nil, city_id:1)
Neighborhood.create(name:"Cory - Merrill", description: nil, city_id:1)
Neighborhood.create(name:"Belcaro", description: nil, city_id:1)
Neighborhood.create(name:"Washington Park", description: nil, city_id:1)
Neighborhood.create(name:"Washington Park West", description: nil, city_id:1)
Neighborhood.create(name:"Speer", description: nil, city_id:1)
Neighborhood.create(name:"Cherry Creek", description: nil, city_id:1)
Neighborhood.create(name:"Country Club", description: nil, city_id:1)
Neighborhood.create(name:"Congress Park", description: nil, city_id:1)
Neighborhood.create(name:"City Park", description: nil, city_id:1)
Neighborhood.create(name:"Clayton", description: nil, city_id:1)
Neighborhood.create(name:"Skyland", description: nil, city_id:1)
Neighborhood.create(name:"Cole", description: nil, city_id:1)
Neighborhood.create(name:"Marston", description: nil, city_id:1)
Neighborhood.create(name:"Washington Virginia Vale", description: nil, city_id:1)
Neighborhood.create(name:"Barnum", description: nil, city_id:1)
Neighborhood.create(name:"Barnum West", description: nil, city_id:1)
Neighborhood.create(name:"Villa Park", description: nil, city_id:1)
Neighborhood.create(name:"West Colfax", description: nil, city_id:1)
Neighborhood.create(name:"West Highland", description: nil, city_id:1)
Neighborhood.create(name:"Sloan Lake", description: nil, city_id:1)
Neighborhood.create(name:"Berkeley", description: nil, city_id:1)
Neighborhood.create(name:"Regis", description: nil, city_id:1)
Neighborhood.create(name:"Lincoln Park", description: nil, city_id:1)
Neighborhood.create(name:"City Park West", description: nil, city_id:1)
Neighborhood.create(name:"Whittier", description: nil, city_id:1)
Neighborhood.create(name:"Capitol Hill", description: nil, city_id:1)
Neighborhood.create(name:"North Capitol Hill", description: nil, city_id:1)
Neighborhood.create(name:"Civic Center", description: nil, city_id:1)
Neighborhood.create(name:"CBD", description: nil, city_id:1)
Neighborhood.create(name:"Union Station", description: nil, city_id:1)
Neighborhood.create(name:"Five Points", description: nil, city_id:1)
Neighborhood.create(name:"Stapleton", description: nil, city_id:1)
Neighborhood.create(name:"Montbello", description: nil, city_id:1)
Neighborhood.create(name:"Lowry Field", description: nil, city_id:1)
